### ISSUE TITLE
Fix indentation quirks for bzl filetype

### ISSUE THREAD

**Issue by dbarnett** [bazelbuild/vim-ft-bzl#1]
Indentation for BUILD files is slightly different from indentation for python. For instance, in BUILD code like

``` python
py_library(
  name = "foo",
)
```

The close paren should not be indented at all.

We should configure an indentexpr specifically for BUILD files that reflects this and other slight style differences.

**Comment by chaoren** [comment]
The default indent (`GetPythonIndent`) looks like this right now:

```
cc_binary(
        name = "hello-world",
        srcs = ["hello-world.cc"],
        deps = [
                ":hello-time",
                "//lib:hello-greet",
                ],
        )
```

Note that `shiftwidth` is set to 4, but the indent is 8 for some reason.

[The indent from python-mode](https://github.com/klen/python-mode/blob/master/autoload/pymode/indent.vim#L10) looks like this:

```
cc_binary(
    name = "hello-world",
    srcs = ["hello-world.cc"],
    deps = [
        ":hello-time",
        "//lib:hello-greet",
    ],
)
```

If you just borrow that indentexpr, you can already get a much superior indent.

**Comment by chaoren** [comment]
Never mind. It's LGPL. 😞
