### ISSUE TITLE
Recognize *.BUILD files

### ISSUE THREAD

**Issue by RenatoUtsch** [bazelbuild/vim-ft-bzl#11]
(sorry about the weird old title)

I noticed that `*.BUILD` files are not recognized by this plugin as being BUILD files. Could you please add support for recognizing these files as being of the `bzl` filetype? It's very useful for formatting `new_http_archive` and `new_git_repository` specified build files. For example:

https://github.com/tensorflow/tensorflow/blob/master/third_party/jpeg/jpeg.BUILD

**Comment by artasparks** [comment]
Easy enough to add of course, but do you happen to know the expected scheme for BUILD file naming? I looked around for it on https://bazel.build/versions/master/docs/build-ref.html but couldn't find anything definitive.

(Might as well add any other known BUILD patterns).

**Comment by artasparks** [comment]
Also, for reference this is an offshoot from https://github.com/google/vim-codefmt/issues/82

**Comment by RenatoUtsch** [comment]
Unfortunately I don't know, but from looking at Bazel's and TensorFlow's projects it looks like they use `*.BUILD` and also `BUILD.*`:

https://github.com/bazelbuild/bazel/blob/master/tools/cpp/BUILD.tpl

So it's a good start.

**Comment by RenatoUtsch** [comment]
I've proposed a pull request for this in #12 .

**Comment by RenatoUtsch** [comment]
Fixed by #12.
