### ISSUE TITLE
Move to bazelbuild GitHub org

### ISSUE THREAD

**Issue by davidzchen** [bazelbuild/vim-ft-bzl#9]
For better discoverability, I think it would be better to move this repo under the github.com/bazelbuild org.

**Comment by davidzchen** [comment]
+cc @damienmg @kchodorow

**Comment by dbarnett** [comment]
Fine by me. Vim team in Google org can still keep repo access, right?

**Comment by davidzchen** [comment]
Of course, that won't be a problem.

**Comment by damienmg** [comment]
Fine by me. It will just be a transfer of repository. Maybe we should ask github owners at Google though.

**Comment by dbarnett** [comment]
Who needs to initiate this transfer? I checked, and I don't have permission to create a repo inside bazelbuild.

**Comment by damienmg** [comment]
So if Will has no objection then either I or @kchodorow needs admin access to this repository to do the move (or Will who is admin on both google and bazelbuild can do it).

**Comment by willnorris** [comment]
oops sorry, I missed this.  Let me know if you want me to go ahead and do it now(-ish), or at a coordinated date/time.

**Comment by dbarnett** [comment]
Not a huge risk either way since nobody needs this repo directly at the moment (current version has been merged upstream into both vim and neovim), and IIRC it can still be cloned from the old repo path. Not a bad idea to wait until you and I are both generally available in case there's some gotcha with permissions, though.

**Comment by willnorris** [comment]
Back in the office now, so let me know when to proceed.

**Comment by dbarnett** [comment]
Go for it. I'm back in the office now, too.

**Comment by willnorris** [comment]
Transfer complete (sorry for the delay, I completely lost track of this).  @dbarnett and @damienmg still have admin access and can add others as needed.

**Comment by dbarnett** [comment]
Thanks, Will!

**Comment by dbarnett** [comment]
Only links I haven't updated yet are the ones in vim's merged files from this repo: https://github.com/vim/vim/blob/60cce2f/runtime/ftplugin/bzl.vim#L3. Old paths will continue to work as an alias, so we'll just update those if/when we have other changes to merge.
